### ISSUE TITLE
Cannot find "/index.js" in docute-evanyou@0.5.0

### ISSUE THREAD

**Issue by djyde** [egoist/docute-evanyou#2]
https://unpkg.com/docute-evanyou is broken.

**Comment by egoist** [comment]
there's no `index.js`, unpkg.com somehow didn't recognize `main` field which is pointed to `dist/evanyou.js`, https://unpkg.com/preact doesn't work either.

**Comment by djyde** [comment]
Uh... Using https://unpkg.com/docute-evanyou@0.5.0/dist/evanyou.js instead
